"""add user_settings table

Revision ID: fc16f9e174e9
Revises: aaea80e1b6e8
Create Date: 2026-04-27 12:38:01.147133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc16f9e174e9'
down_revision: Union[str, Sequence[str], None] = 'aaea80e1b6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('gemini_api_key_encrypted', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
